### ISSUE TITLE
Additional Information not validating form fields

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-baltcogo#116]
You can submit the form without any data.

**Comment by danfox01** [comment]
Validation is borked here. Can't tell exactly what's going on, but all of the fields are showing error messages by default, and the label styling seems to be a mix of the error state CSS.

![FireShot Capture 093 - Request Service or Report a Problem - Baltimore County_ - dev baltimorecountymd gov](https://user-images.githubusercontent.com/13049389/61822753-55a03b80-ae28-11e9-9226-43243bf0483c.png)

**Comment by danfox01** [comment]
**Update:** Validation might actually be fine, but the field styling is off. Take a look at the Sign up field for an example of the validation markup and style.

**Comment by tmccoy529** [comment]
@danfox01 this was missing a div that held the correct CSS. This has been added now.

**Comment by danfox01** [comment]
Looks good.
