### ISSUE TITLE
Register for an account: "Account already exists" error message styling

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#128]
When a user tries to sign up using an email that's already in use, they receive an inline error message. Ideally, the field name and label should also turn red when this happens, like other inline errors.

I think a class of error just needs to be applied to the containing div.

**Comment by tmccoy529** [comment]
@danfox01 This was also an issue inside of the map. When the map was out of the Baltimore county area the error message appeared but the text box and label did not highlight. This has been fixed for both of these sections.

**Comment by danfox01** [comment]
Released to prod w/ HF #169 . Confirmed fixed.
