### ISSUE TITLE
Identify and handle errors for server failures

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#136]
Discovered while testing error messaging with request blocking turned on. We need failure messages at a few places in the UI where the user is making a server request. For example:

Sign in
Sign up
Reset password

**Comment by danfox01** [comment]
@jdomasky confirmed these error messages are working, however we need to tweak what they say.

Currently they say "Network error."

Please update to, "We're having trouble connecting to the server. Please try again in a few minutes."

**Comment by tmccoy529** [comment]
@jdomasky @danfox01 the text has been changed and this is back in test.

**Comment by jdomasky** [comment]
@tmccoy529 @danfox01 Thank you. Will resuming testing today--shortly.

**Comment by jdomasky** [comment]
Looks good. This issue has passed testing.
