### ISSUE TITLE
Pre-Go Live Implementation

### ISSUE THREAD

**Issue by tmccoy529** [baltimorecounty/react-baltcogo#140]
@danfox01 @martypowell @sgrg1 
I wanted to gather all the go live requirements here and also list items that need to happen prior to go live. 

Basically the move will be three parts.

First Is to move the services over
Second will be to move the compiled code over
Third will be testing

Things to do prior to Go Live:
Since we are using a json file to populate text fields that should be moved over prior as we will need to update the code to point to those file locations.

Im sure there are some SE things other than the file locations that should probably be done prior but I'm no expert on SE so if anyone needs to fill in he blanks if any that would be great.

My main concern with the services move is that the webconfig MUST be copied over as well and that seems to be when things hit the fan. So I don't know if we can get a copy of the prod Web Config and just add the new API locations to it leaving the rest along and add that to the bundle for Steve to copy over. Might make things easier.

Anyway feel free to add to this

**Comment by tmccoy529** [comment]
These are the instructions I will be sending to Steve for release of the new service. Is there anything I am missing? Its pretty straight forward but wanted to capture it here in case we wanted to make changes.

1.	The following path contains the production data on testservices box : C:\inetpub\wwwroot\prod-services 7-31-2019 (yet to be created)
2.	NSU to take a backup of services.baltimorecountymd.gov
3.	Replace all files in services.baltimorecountymd.gov with the prod files from the testservices box in step 1
4.      Ensure that webconfig is copied over as well
5.     Recycle the app pool
6.	Developer and team will execute test plan to hit all key elements of new application.

**Comment by martypowell** [comment]
that sound about right to me.

**Comment by tmccoy529** [comment]
@martypowell what do you think about copying over the prod web config and modifying it and pushing that back up with the bundle? I think something went crazy with it last time and we had to roll back. I don't remember what the issue was but I think it generates a token or something when we compile and it really didn't like it (which could mean I published in release mode not production mode).

**Comment by martypowell** [comment]
i would prefer is we use the process. could we try a "productuion" try run on testservices, monday or tuesday to verify the prod release process works?

**Comment by tmccoy529** [comment]
yeah that sounds good to me
