### ISSUE TITLE
Some Accela issue types log the CitySourced ID number instead of the string the user inputs in the "City" field

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#145]
To replicate:

- Choose **Building and Development > Plumbing work without a permit**
- Fill out the entire form and make sure to enter a valid city name in "Additional Information" form
- Log into CitySourced console and note that the data in the "City" field is showing a Citysourced ID number, not the string you entered.

**Comment by tmccoy529** [comment]
@danfox, I think I have a fix for this. Looks like we had a duplicate entry for city zip and address that was populating the ID's instead of text and then also the text. Ill be pushing this up soon.

**Comment by danfox01** [comment]
Apprears resolve to me. Moving to done and will  have @jdomasky retest before closing.

**Comment by tmccoy529** [comment]
@danfox01 should this issue be closed?

**Comment by danfox01** [comment]
Yup! Thanks.
