### ISSUE TITLE
Update Report Lookup for API 2.0

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#155]
We decided to hold off updating the report lookup tool while we worked on the reporter. Now that the reporter is done, we should revisit the lookup ASAP. It will be a much smaller lift.

I know this is documented in TFS but I want to add it here. "Put up a maintenance page and worry about the reporter later" was good foxhole logic but now I'm realizing how much it sucks that we're basically telling people, "Sorry, this is unavailable for some unknown period of time."

Putting this at the top of the list.

**Comment by tmccoy529** [comment]
@danfox01 @martypowell 

While creating the lookup report page Im running into a lot of head scratches and questions.

I see that we have a bunch of report types:
•	AccelaAnimal
•	AccelaCode
•	BaltcoGo,
•	FastRack/ECMS

Some of these appear to redirect to a different portal for the users to input their codes but others display a response from an API call. FasTrack/ECMS (I think these are the same) looks like we build a login API then we send a correspondence ID to another API call and display the info back on our side like the baltcogo lookup. I have no idea what one of these reports is supposed to look like or what data is even returned. Based on TFS FasTrack is decommissioned, so do I even need to worry about this? Should we remove the logo now also?

Finally, I have never actually seen a baltcogo report so I have no idea how it displays. The response we get back from Citysourced has about 50 items in it from dates to ID's and lord only knows what else. What are we displaying to the users? Do we have a mockup or screen grab of one of these reports?

**Comment by danfox01** [comment]
@tmccoy529 I think I can help you square some of this away. Heading to meeting in a few but will back with you soon -- hopefully by early afternoon. In the meantime, if you're stumped and want to break off some lower-priority items that look easy, feel free.

**Comment by danfox01** [comment]
@tmccoy529 I confirmed that we **do not** need Fastrack functionality included any longer.
