### ISSUE TITLE
Eliminate extra padding around reporter container

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#161]
There's 15px of extra padding on both sides of the reporter container. It looks like it's coming from the "container" class. This eats up some much needed real estate on mobile. Let's remove or override so that the edges of the reporter are aligned with the content.

**Comment by danfox01** [comment]
I'm actually not seeing this fix. I thought I did but I was looking in the wrong place.

**Comment by tmccoy529** [comment]
@danfox01 no you probably did see it but I pushed a different branch up to test the get report section that didn't have the fix in it. Ive pushed up the correct branch again. Fix should be in now.

**Comment by danfox01** [comment]
Released to prod w/ HF #169 . Confirmed fixed.
