### ISSUE TITLE
Routing to top-level categories does not work

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#164]
Routing to sub-categories works as expected, but top-level categories don't work.

**To replicate**:
- Subcategory example (works): https://www.baltimorecountymd.gov/iwant/report.html?categoryid=1011495#/
- Top-level category (does not work): https://www.baltimorecountymd.gov/iwant/report.html?categoryid=1011459#/

**Expected behavior:**
Routing should work for top-level categories. The first drop down should be ore-filled with the category type. The second-level drop down should show "Please select" be default and show the appropriate sub-items.

**Comment by tmccoy529** [comment]
@danfox01 this has been resolved. Example here:
https://dev.baltimorecountymd.gov/iwant/report-test.html?categoryid=1024827#/

**Comment by danfox01** [comment]
Released to prod w/ HF #169 . Confirmed fixed.
