### ISSUE TITLE
Conditional Message Styling

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#17]
Example, select **Water and Sewer Issues > Sewer Issues**

- Conditional messages should be wrapped in `<div class="alert-information bc_alert">` with a icon of `fa fa-icon fa-2x fa-info-circle`
- HTML from the JSON file should be rendered live on the page. (Markup is currently being pulled in as plain text)

**Comment by tmccoy529** [comment]
I believe this has been resolved
