### ISSUE TITLE
Map pin should drop where the user clicks, and the map should not recenter

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#172]
#152 resolved an issue with map reloading every time a user clicks, but there are still a few UI quirks.

**Current behavior:**
- The map always recenters where the user clicks, which is disorienting. 

**Expected behavior:**
- The pin should drop wherever the user taps/clicks. The map should not recenter when his happens.

**More detail:**
- Take a look at the archived Angular version of Reporter tool to see map behavior: http://staging.baltimorecountymd.gov/iwant/backup_190731/report.html
- This doc you may provide the info you need on animation: https://developers.google.com/maps/documentation/javascript/examples/marker-animations

**Comment by danfox01** [comment]
Updated to split into two issues. See #176

**Comment by danfox01** [comment]
@sgrg1 @tmccoy529 @martypowell, looks like this one did not pass testing. Please see comment below from @jdomasky. If you have questions, you can hit him up directly

> This only works in desktop Chrome and desktop Firefox. In fact, the map can only be used in desktop Chrome and desktop Firefox.
> 
> On iPhone Safari, Android Chrome, IE 11 and desktop Edge, when the user clicks on the map, the entire CitySourced Reporter container disappears. With the container missing, the page only displays the intro paragraphs and the “Other Popular Issues to Report” table. Reloading the page is the only way the Reporter container can be made to reappear.
> 

Moving back to development.

**Comment by tmccoy529** [comment]
So this is due to adding animations which had not been added prior. Animations are not supported and will need a poly fill to fix. In the mean time we can remove that animation property to get these through testing. Will let you know when this is ready to test again.

**Comment by jdomasky** [comment]
Okay.

**Comment by tmccoy529** [comment]
@jdomasky @danfox01 @sgrg1 @martypowell this has been moved back to test. IE11 looks good but I cant test the other formats. So fingers crossed.

**Comment by jdomasky** [comment]
@tmccoy529 @danfox01 @sgrg1 @martypowell Thank you. Will resuming testing shortly.

**Comment by jdomasky** [comment]
@tmccoy529 @danfox01 @sgrg1 @martypowell This issue passed testing. The map works fine and it does not recenter in all browsers tested.
