### ISSUE TITLE
Changes to "Describe the Problem"

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#19]
On the **Provide Details** panel, the **Describe the Problem** field needs the following changes:

- Field correctly fires an error is no text is entered, but the user is still able to advance to the next panel. The user should not be able to advance until the error is resolved.
- It looks like we have some inline styles applied to set the size of the text area. We want to do this with CSS. I think he just need to wrap the label and field in `<div class="cs-form-control">` and it should style correctly without any other changes. (As noted in another issue, we want to wrap every field/label/error group in the same class.)

**Comment by danfox01** [comment]
Some of these issues were resolved yesterday; some still exist. Revising issue to reflect what's left.

**Comment by tmccoy529** [comment]
@danfox01 I removed inline styles, added CSS class. Users wont be able to progress now but not the correct way. We are still using the disabled button way which is going to be addressed in #22

**Comment by danfox01** [comment]
Thanks!
