### ISSUE TITLE
Kill extra <br> tags in markup

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#20]
It looks like the markup contains a number of `<br>` tags for spacing out the body of the form. For example on the map page, there are four `<br>`s after `<div toggler>`. There are a few random ones on some other panels as well.

I think we want to kill these and rely on CSS for spacing.

**Comment by tmccoy529** [comment]
I think these have all been removed

**Comment by danfox01** [comment]
I think so too. Thanks.
