### ISSUE TITLE
Inline error state markup and style

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#21]
Looks like we need a couple of tweaks to the error state presentation:
- The error message itself renders correctly, but when an error state is active the field and label should also be red.
- We just need to adjust the markup to match what the Angular app did, and adjust what the conditional elements are.

**Current Markup:**

```
<label for="requestType">Request Category</label>
<select name="requestType">...</select>
<div class="error">
   <p role="alert" class="error-message"></p>
</div>
```

**I think what we want is something like this:
Default state:**
```
<div class="cs-form-control">
   <label for="requestType">Request Category</label>
   <select name="requestType">...</select>
</div>
```
**Error State:**
```
<div class="cs-form-control error">
   <label for="requestType">Request Category</label>
   <select name="requestType">...</select>
   <p role="alert" class="error-message">This is the error message text</p>
</div>
```

Note that the parent div is always there, and when the error is active we just add the "error" class to it. Additionally, the p tag with "error-message" class and the text get added conditionally at the same time.

**Comment by tmccoy529** [comment]
The general idea behind this has been fixed. We are still missing some fields for validations but any new fields will mimic this format.

**Comment by danfox01** [comment]
Confirmed in markup on the first panel. @tmccoy529 Do you want me to close this, or leave it open?

**Comment by tmccoy529** [comment]
@danfox01 lets leave it open for now. Its a good reference in case we miss a section.

**Comment by danfox01** [comment]
10-4

**Comment by danfox01** [comment]
@tmccoy529, we need to wrap ever label/field pair with `<div class="cs-form-control error"</div>` on the Sign In and Register Page. That will fix a number of layout issues.

**Comment by danfox01** [comment]
One more to wrap: https://dev.baltimorecountymd.gov/iwant/report-TEST.html#/ResetPassword

**Comment by tmccoy529** [comment]
Ive added these to the create account and password reset.

**Comment by danfox01** [comment]
I think we are all good. If we find more we will reopen. Or we'll just fix it. Whatever we feel like.
