### ISSUE TITLE
Buttons should be enabled but not functional until all required fields are complete

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#22]
The way this is being handled isn't necessarily bad, but I think a better solution is to leave buttons clickable so they can fire error states when clicked. Otherwise the user may not be able to easily tell why the form isn't allowed to advance.

**Current behavior:**

Buttons have a state of "disabled" until all required fields are filled. This grays out the button and makes it unclickable.

**Expected behavior:**

Buttons are still be visually "active" and can be clicked. But if required fields are still needed, the form won't advance and any incomplete fields will enter error state. See the behavior of the current app for an example: https://www.baltimorecountymd.gov/iwant/report.html

**Comment by danfox01** [comment]
FYI, I don't know if this helps but I was looking at Sanjaya's original build here: https://xpl6nn8vp.codesandbox.io/ before we moved to SE, and it looks like the buttons and error messages are working the way we want them to (buttons are clickable errors either fire on blur, or when the "next" button is clicked). i'm sure it's more complex in SE but maybe this'll help.

**Comment by danfox01** [comment]
@tmccoy529 this looks resolved to me. Can you please confirm?

**Comment by danfox01** [comment]
Per @tmccoy529 -- still experiencing issues with this. The buttons on each panels are actually links, which don't have a submit action is making this wonky. Still investigating.

**Comment by martypowell** [comment]
@tmccoy529 @danfox01 any update on this?

**Comment by danfox01** [comment]
I think we can close this one. I want to revisit in the future -- will create a backlog item.
