### ISSUE TITLE
Modal is no longer modaling

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#23]
For the "Why Do I Need an Account? modal, I know this was working before, but it now just appearing at the bottom of the page. I'm guessing a result of the markup changes?

**Comment by danfox01** [comment]
Issue resolved by adding the necessary Bootstrap 4 modal and button classes to a separate CSS file and calling it in the SE page `<head>` on this page only.

Kinda cheap but it works. FYI @tmccoy529, this CSS will need to be added to source control.

**Comment by martypowell** [comment]
@danfox01 @tmccoy529 the css is in the project, should we close?

**Comment by danfox01** [comment]
If the CSS is there, yup.
