### ISSUE TITLE
Issues with a "shouldDisableForm" flag should hide "Next" button upon selection

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#27]
Issues with a JSON key/value of `"shouldDisableForm": true` should not be allowed to advance to the next panel.

- When a user is not logged in the, the "Sign In," "Log In" and "Why Do I Need to Do This?" buttons should immediately be hidden when one of these issues is selected.

- When a user is logged in, the "Next" button should be immediately hidden when one of these issues is selected.

**Comment by danfox01** [comment]
@tmccoy529 this looks to me to be fixed, can you confirm you addressed this?

**Comment by tmccoy529** [comment]
Sorry, yes this has been addressed and should be working correctly now.

**Comment by danfox01** [comment]
Thanks. Wanted to confirm before closing.
