### ISSUE TITLE
Edits to inline error messages

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#30]
Need some text edits to the error messages that get thrown for inline field validation:

```
  "errors": {
    "requestType": "Please select a request category.",
    "subRequestType": "Please select a request category.",
    "petType": "Please select a pet type.",
    "animalColorType": "Please select a pet color.",
    "serviceDescription": "Service Description is required",
    "streeAddress": "Please enter your street address.",
    "zipCode": "Please enter a valid five-digit ZIP code.",
    "location": "You must select a location inside Baltimore County.",
    "describeTheProblem": "Please enter a description for your report.",
    "Email": "Please enter your email address.",
    "Password": "Please enter your password."
```

**A few notes:**

- I'm not totally sure where the error messages for the [Sign Up form](https://dev.baltimorecountymd.gov/iwant/report-TEST.html#/SignUpForm) are coming from. For example, I don't see props for first name, last name or phone.
- It also looks like we _might_ be using the same error message instance for email and password whether a user is signing up or signing in, and they actually need to be different.  For example, when signing in, a user would be asked something like, "**Please enter your password**." but when signing up it would be, "**Please choose a password. Passwords must be at least 8 characters long and contain blah blah blah**"

**Comment by tmccoy529** [comment]
These have been updated.

**Comment by danfox01** [comment]
Error messages look good. Going to leave this open for now since there are a handful of local validation error messages for that still aren't accounted for.

**Comment by danfox01** [comment]
Closing. Will open separate issues for the remaining fields that don't validate properly.
