### ISSUE TITLE
Add phone number validation.

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#31]
On "Register for an Account" panel (https://dev.baltimorecountymd.gov/iwant/report-TEST.html#/SignUpForm), the phone number field needs validation rules and an error message applied.

- The input should allow phones in these common formats:
  - xxx-xxx-xxxx
  - (xxx)xxx-xxx
  - xxx.xxx.xxxx
  - xxx xxx xxxx
  - xxxxxxxxxx

 - Basically, as long as there are 10 digits, the UI should not care if there are hyphens, periods, spaces, or parentheses.

- When the user submits the form, the application should change the format of the phone in the background to the format that CitySourced requires, which is xxx-xxx-xxxx.

- If the user doesn't provide a phone, doesn't include enough digits, or includes any letters or symbols other than the ones mentioned above, this error should be fired:

**Please enter your phone number in the following format: 410-555-1212.**

**Comment by martypowell** [comment]
this has been addressed and will be pushed when @tmccoy529 is ready with his workflow changes.

**Comment by martypowell** [comment]
@danfox01 this should be available in dev.

**Comment by danfox01** [comment]
Confirmed. Works great.
