### ISSUE TITLE
Change non-field labels to P tags

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#33]
The `<label>` element is used in a few places that should just be `<p>` tags. Please change the following from `<label>` to `<p>`:

On https://dev.baltimorecountymd.gov/iwant/report-TEST.html#/ServiceRequestForm:
- You're signed in as Dan Fox
- Not Dan? Log in to a different account. 

On https://dev.baltimorecountymd.gov/iwant/report-TEST.html#/SignInForm:
 - Forgot password?
 - Don't have an account? Sign up

On: https://dev.baltimorecountymd.gov/iwant/report-TEST.html#/SignUpForm
 - Already have an account? Sign In

On https://dev.baltimorecountymd.gov/iwant/report-TEST.html#/ResetPassword
 - Don't have an account? Sign up
 - Remember your password? Sign In

**Comment by tmccoy529** [comment]
This has been updated.

**Comment by danfox01** [comment]
Perfect. And of course now that the P tags are there, the spacing is off. Can you please remove the <br> tags that are after these elements as well?

**Comment by tmccoy529** [comment]
done and done. Let me know if I missed any.

**Comment by danfox01** [comment]
If you missed any, I did too. Thanks.
