### ISSUE TITLE
Update UI flow behavior for issues marked "requiresLocation: false"

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#34]
Right now the only category with this flag is **Website Issues** but it could apply to others in the future. Basically, for these issues we want to hide the location section and pass the address/lat/long for 400 washington avenue in the background.

**Current behavior:**
Selecting **Website Issues** spawns a "Describe the Problem" field on the first panel and still allows the user to select a location on the second panel.

**Expected behavior:**
Selecting **Website Issues** should not alter the first panel. On the second panel ("Provide Details") the address and map section should be hidden, and the system should pass a location of 400 Washington Avenue in the background. I am not sure of the exact lat/long, but you can prob grab it from the Angular version. The user should be unaware we are passing this info -- as far as they can see, the location just isn't required.

**Comment by tmccoy529** [comment]
This should be fixed now

**Comment by danfox01** [comment]
This works. I was actually envisioning something a little different design-wise, but this satisfies the functionality. We can address changes later.
