### ISSUE TITLE
Add error and success messages upon form completion

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#35]
When an issue is successfully submitted to the system, the user should receive a success message. I think this markup from the Angular version should do it, plus whatever needs to be added conditionally to show/hide:

**Success Message**
```
<div role="alert" class="bc-citysourced-reporter-alert alert-success">
        <h2>Your Submission Has Been Received</h2>
        <p>
            Thank you for submitting your report. You will receive an email in a
            few minutes with your tracking number and additional information.
        </p>
        <p>
            You can track your status online at any time by entering your
            tracking number at
            <a href="/followup" title="Track your issue status online.">www.baltimorecountymd.gov/followup</a>.
        </p>
    </div>
```

**Failure Message**
```
<div role="alert" class="bc-citysourced-reporter-alert alert-warning">
        <h2>Your Report Was Not Submitted</h2>
        <p>
            We're sorry, we encountered a problem processing your submission. We are working to resolve this issue as quickly as possible.
        </p>
    </div>
```

It would probably be ideal if the entire form disappears when the success message appears. If possible, the failure message should appear above the main form so that the user can try resubmitting.

**Comment by martypowell** [comment]
Responses from the server should also be handled. One example of a missing error, is an invalid password.

**Comment by danfox01** [comment]
@tmccoy529 @martypowell is there any way to get a list of the server responses for various actions, or should we just start with the obvious ones?

**Comment by martypowell** [comment]
@danfox01 we will just need to work through it.

note to self, invalid addresses need to be handled.

**Comment by tmccoy529** [comment]
@danfox01 @martypowell, incorrect login, no email address on file (password reset), invalid address I think are the major errors we get back aside from the "you suck" message when theres an actual error on our end. Other than that its all "congrats on sucking" for all the successes.

**Comment by danfox01** [comment]
- For incorrect login, let's say: The username or password you entered is incorrect. Please try again. (Ideally, we should try to identify if the username is valid, or if it's the password that's the problem. But for now, this'll do.)

-For no email address on file for password reset: Sorry, that email address isn't in our system. Please try again, or register for an account.

**Comment by martypowell** [comment]
@danfox01 actually the message you suggest is preferred, this is a good [thread](https://ux.stackexchange.com/a/13523/30814) on the topic.

**Comment by martypowell** [comment]
We will continue work on this once the confirmation page style issues are resolved.

**Comment by danfox01** [comment]
Successfully trigger a success and a failure. Not exhaustive tests, but these look good.
