### ISSUE TITLE
Changes to workflow for address entry

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#40]
**Basic requirements:**

- The user's address, city and ZIP should not be collected during account signup. Sign-up should only require First Name, Last Name, Phone, Email and Password.
- **For Accela issues only,** there should be a final panel called "Additional Information" that requires address, city and ZIP. (I believe state is also passed but should not be shown to the user because it's always Maryland).
 - **For non-Accela issues** the final panel does not appear and users do not provide address information.

Note, this also means that the location of the Submit button changes based on the issue type. Non-Accela issues should show the **Submit** button on the "Provide Details" panel. Accela issue show it on the "Additional Information" panel.

FYI @tmccoy529

**Comment by tmccoy529** [comment]
@danfox01 @sgrg1 @martypowell we will need to remove the final submit button and place it into a component or control. This way we can swap this button out and build it where its needed reducing duplicate code. The criteria for displaying this button on the Provide Details page is if we have a requestTypeAddressID. If this does not have a value either null or undefined the AdditionalInfo page will not be displayed and the Provide Details page will be the final form to submit. If this value does exist then we know its an Accela type and the Additional Info page will need to appear and allow the user to enter their address. We will need to run the address verification endpoint against what is entered and handle errors accordingly. Tabs will have to reflect this as well at the top. Registration address will have to be removed. Sing In will no longer grab the contact address and prepopulate the additional information form. 

I have started this work but requested Sanjay to handle the buttons.

**Comment by tmccoy529** [comment]
@danfox01 This has been completed.

**Comment by danfox01** [comment]
Looks great.
