### ISSUE TITLE
Re-create Forms

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-baltcogo#6]
We going to try and use [formik](https://github.com/jaredpalmer/formik) to build our forms and [Joi](https://github.com/hapijs/joi). If Joi works out to be too complicated the we will use [Yup](https://github.com/jquense/yup) as described in the formik docs.

Please submit one pull request per form.

More details to follow:

Forms to create

- **How Can We Help**
  - Request Category - Select Input - required
  - Request Sub-Category - Select Input - required
  - Sign In - Button type button
  - Register - Button type button
  - "Why do I need this?" - link (more info to follow)
- **Sign In**
  - Email Address - email input - required, is a valid email address
  - Password - password input
  - Forgot your password - link (will need to utilize the api)
  - Sign In and Continue - button type button
  - Note we will need to handle an invalid username / password combo, *more to come
- **Register**
  - First Name - input text - required
  - Last Name - input text - required
  - Email Address - input email - required
  - Password - input password - required, *probably need some requirements for strength
  - Sign Up and Continue - button type button
  - Note we will need to handle a valid password requirements which are yet to be determined
- **Provide Details**
  - Add a Location - react-autocomplete - required
  - Map Control - add a placeholder, this will be addressed in a later issue
  - Describe the problem - textarea - required (minimum amount of characters?)
- **Additional Information (optional)**
  - Note accela only??>
  - Your Street Address - input text - required
  - Your City - input text - required
  - Your ZIP Code - input number pattern="[0-9]*" - required (this will force a number pad on mobile)

**Comment by martypowell** [comment]
fyi @danfox01

**Comment by danfox01** [comment]
@sgrg1 How are things going with rebuilding these in React?

**Comment by sgrg1** [comment]
@danfox01 Im on it .  Development is in process.

**Comment by danfox01** [comment]
Thanks Sanjay! Do you have an estimate of when we might have a basic prototype for review? It doesn't have to be complete but the sooner I can get my hands on something the sooner I can start getting feedback to you.
