### ISSUE TITLE
Enter key in address field takes user back to previous page

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#67]
**Issue:**

Hitting enter while the address input field is selected takes the user back to the previous screen.

**Expected behavior:**

In most cases, hitting enter while in this field should do nothing. The exception is if using the keyboard to cycle through autocomplete addresses -- enter should select the highlighted address. It should never take the user backward.

**To replicate:**

- Advance to the second panel, "Provide Details" and click inside the address input box.
- Hit enter.
- Enjoy the trip back to the previous panel.

**Comment by tmccoy529** [comment]
@danfox01 @sgrg1 I believe Sanjay had started looking into this already.

**Comment by danfox01** [comment]
Resolved.
