### ISSUE TITLE
Website issue asks for description twice

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#70]
To replicate select Website Issue > Broken link. The “Service Request Description” field should not be displayed on the first panel.

**Comment by tmccoy529** [comment]
@danfox01 do you know if there is ever a criteria where the description should be on the first panel? If not then I will just delete it entirely from the first panel.

**Comment by danfox01** [comment]
Per our Jabber convo, I don't think this is ever needed. Thanks!

**Comment by danfox01** [comment]
Confirmed. Thanks guys.
