### ISSUE TITLE
Map pin location changes when moving back and forth between panels

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#72]
To replicate:

- Select an issue and advance to the Provide Details panel.
- Enter a valid address (expand map to note the pin location)
- Select "Previous" then "Next"
- Note that the address is retained but the pin location has moved back to the Historic Courthouse.

**Comment by sgrg1** [comment]
im looking into it

**Comment by martypowell** [comment]
@tmccoy529 we should probably keep this open until jason confirms this? @danfox01 any thoughts?
