### ISSUE TITLE
Add UI feedback for password reset

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#73]
We need to provide some on-screen feedback for password reset requests: https://dev.baltimorecountymd.gov/iwant/report-TEST.html#/ResetPassword

When the request is successfully submitted and the user is returned to the sign in screen, we should display the following text in a green callout above the inputs:

> Your request to reset your password has been received. Please check your email for a link to reset your password, then return to this page to log in.

It would be super-duper ideal if we could call back the email account they need to check based on the request the submitted, e.g.:
> A link to reset your password has been sent to {email address}. Please follow the instructions and return to this page to log in.

Only if its super easy - part of the response or something.

**Comment by danfox01** [comment]
Sweet.

**Comment by tmccoy529** [comment]
@martypowell with the changes you made to the alert component in the branch that is on hold, would it make it easier to accomplish this task? If so then why don't you merge that branch and then tackle this one? If not then we will continue like before.

**Comment by martypowell** [comment]
In that pr a `Note` component was created that superficially styled an alert as a "note". I think you should be able to use the existing `Alert` component if you want to avoid any rework or...

If thats kinda what you are looking foward you could always just grab this [commit](https://github.com/baltimorecounty/react-baltcogo/pull/86/commits/c5cd0fe4699fc23061e146a81f6aa8a37cd46149) and cherry pick.

The process to do that is.

1. Ensure you are on a feature branch
2. `git cherry-pick c5cd0fe4699fc23061e146a81f6aa8a37cd46149`
3. Commit your changes

Then you can call the note component like

```jsx
<Note>{yourNoteGoesHere}</Note>
```

**Comment by danfox01** [comment]
Looks great.
