### ISSUE TITLE
"Other website problem" fires empty alert box

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#74]
To replicate select **Website Issue > Other website problem** and note the empty conditional note box. I don't see anything in the JSON that's causing this.

**Comment by danfox01** [comment]
Spoke to @martypowell  about this and we determined there is a case that's not accounted for in the new panel arrangement.

If the alert box is triggered for an issue that also disables the form, it should appear on the first panel, as it currently does.

If the alert box is triggered for an issue that does not disable the form (e.g., it's additional information that helps the user submit the issue) then alert box should appear on the "Provide Details" panel.

This is a quick fix for the problem at hand. We may need to re-evaluate the way these alerts are displayed or flagged in the JSON file.

**Comment by martypowell** [comment]
@danfox01 closing this since it's a data issue.

The details of your comment have been added as two issues which can be found here:

- #90 
- #91
