### ISSUE TITLE
Add issue routing by ID

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#77]
URLs should follow this format: https://www.baltimorecountymd.gov/iwant/report.html?categoryId=1011072

**Comment by danfox01** [comment]
This one isn't working for me, unless I'm doing something wrong. The URL format I tried is: https://dev.baltimorecountymd.gov/iwant/report-TEST.html?categoryID=1011200

Moving back to To-Do.

**Comment by martypowell** [comment]
hey @tmccoy529 this looks to maybe be a case issue, dan's example has `ID` instead of `Id`, that could be the issue.

**Comment by danfox01** [comment]
Ideally this would not be be case sensitive -- I'm not sure the usage is consistent on the site, so the most flexible way to implement would be case insensitive.

**Comment by danfox01** [comment]
Did some more thorough testing. This is working in some cases, but not all. Here's what I've found:

- Looks like @martypowell is right about the case: `categoryId` works but` categoryID` doesn't
- Dummy issue types don't seem to work, i.e., `categoryId=D000002`

**Comment by danfox01** [comment]
Update: Categories are not case insensitive and this is working a lot better.

However, dummy issues still not working.

**Comment by danfox01** [comment]
Works!

**Comment by martypowell** [comment]
@tmccoy529 did you make changes to get this to work?
