### ISSUE TITLE
On first panel, user cannot log out if fields are left incomplete

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#84]
**Current behavior:**
On the "How Can We Help?" panel, when a user is logged in, the "Not {user}? Log into a different account?" link only works if both drop downs are selected.

**Expected:**
The user should be able to log out regardless of whether the drop downs are selected.

**To replicate:**
- Select an issue type and log in.
- Go back to the first panel and deselect a drop down.
- Try to log out and be sad.

**Comment by danfox01** [comment]
Just chatted with @tmccoy529. The "Not {user?}" link on the main page should immediately log the user out when clicked, and then take them to the login page. (Currently, it takes them to the login screen without logging them out.)

**Comment by danfox01** [comment]
Log out function works great, but if I log out then return to the first panel by hitting the  button, it looks like this:

![FireShot Capture 094 - Request Service or Report a Problem - Baltimore County_ - dev baltimorecountymd gov](https://user-images.githubusercontent.com/13049389/61823930-c9dbde80-ae2a-11e9-8977-eb2338a8b415.png)

I would expect that once logged out, if I return to the main panel, it should have its original state, i.e. this:
![FireShot Capture 095 - Request Service or Report a Problem - Baltimore County_ - dev baltimorecountymd gov](https://user-images.githubusercontent.com/13049389/61824048-12939780-ae2b-11e9-85c5-72d3afc0119a.png)

**Comment by tmccoy529** [comment]
Yup, its an issue that I have a correction for in another branch. Can you kick that back to in progress so I don't forget about it?

**Comment by danfox01** [comment]
Yup, done. Thanks.
