### ISSUE TITLE
New Categories do not display notes

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-baltcogo#90]
**Steps to Recreate**

1. Modify the categories.json file with a new category. You can use this example:

```json
{
	"name": "Issue with Marty",
	"id": 99999999999,
	"requiresLocation": false,
	"types": [
		{
			"name": "He is too mean.",
			"id": 999999999991,
			"note": "This note should be displayed, but the form should remain enabled."
		},
		{
			"name": "He is the meanest",
			"id": 999999999992,
			"note": "This note should be displayed, and the form should be disabled.",
			"shouldDisableForm": true
		}
	],
	"description": 1024813
}
```

2. Reload the app and test the following categories from the drop down.

3. You will notice that the note does not display in either situation.

Per @danfox01 this can be resolved after initial launch, but needs to be addressed immediately following launch.

**Comment by martypowell** [comment]
This should be resolved based on https://github.com/baltimorecounty/react-baltcogo/pull/86

**Comment by danfox01** [comment]
This looks good. There are a few related items -- if any issues are found I will log there.
