### ISSUE TITLE
Rendering issues with prod JSON data

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-baltcogo#97]
Dropped the prod JSON file into the app, which has more data than the version we've been using in dev, and experienced a few showstoppers. If these need to be broken up into separate issues, let me know:

- "Trash and Recycling" breaks the app
- "Roads and Sidewalks > Icy Conditions" does not render note as expected
- "Pets and Animals > Other" does not render note as expected

**Comment by martypowell** [comment]
@danfox01 when this is done YOu will need to change "Pets and Animals > Other" subcategory note field from "note": '...fkdlafjadlkjfa' to "warning": "...fjdaikljfa;jdfa"

**Comment by danfox01** [comment]
This looks good. I'm moving to done but am keeping open for now -- I want to test the data changes as well before fully signing off.
